[package]
name = "jemclicks"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
evdev = "0.12.0"
evdev-rs = "0.6.0"
yaml-rust = "0.4"
clap = { version = "4.0.14", features = ["derive"] }
